<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ubah</name>
   <tag></tag>
   <elementGuidId>3bd47246-2bfc-427d-9a97-639f302641b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'ubah' or . = 'ubah')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-list-15-menuitem-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'ubah')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b665206e-d6fb-4bff-8bb9-5ad10077f570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-list-15-menuitem-12</value>
      <webElementGuid>af7a077b-83ab-4a10-9aa5-17aff836000c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>d3421b99-284e-433e-95db-d4fca5cc6e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b55b6eff-8cfe-44cf-aa2f-4ddb8a7efa56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-menu__menuitem css-13c7rae</value>
      <webElementGuid>002e594d-a16b-4511-9401-22cbffdf2a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users/db1dcee3-80e5-4ed6-bb83-7b8ce2629682/edit</value>
      <webElementGuid>529dc2ed-3efc-4bac-9cf0-3afee2b4e6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ac901099-2693-4656-943d-41381d0e7bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ubah</value>
      <webElementGuid>26a343fd-a8e0-4ab0-85e9-f1da331a5a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-list-15-menuitem-12&quot;)</value>
      <webElementGuid>ccede7f4-afc2-457b-8819-6b3633758375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu-list-15-menuitem-12']</value>
      <webElementGuid>ec05309f-694c-447e-b0c0-55f78a0bab11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-list-15']/a</value>
      <webElementGuid>5444cd97-e2b5-4f83-bf35-0138efc47da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ubah')]</value>
      <webElementGuid>d76d7d98-28bd-4c89-9687-56ea3a6cec2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kasir'])[2]/following::a[1]</value>
      <webElementGuid>515d79c3-a51e-43d0-91bc-6b012a68bc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='panji12345@gmail.com'])[1]/following::a[1]</value>
      <webElementGuid>22c2c9ed-334d-49bb-aa3f-fdfb664aa845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hapus'])[1]/preceding::a[1]</value>
      <webElementGuid>7fa6eb64-3f36-4c65-9b98-288b1bf0ae07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::a[1]</value>
      <webElementGuid>fec51ccc-ea94-48a7-b4fe-6fb3e572c61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ubah']/parent::*</value>
      <webElementGuid>2ac0629f-21b5-4eac-9880-745344ed682d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/users/db1dcee3-80e5-4ed6-bb83-7b8ce2629682/edit')]</value>
      <webElementGuid>3ec4886a-082e-47cc-a099-2344375eb07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/a</value>
      <webElementGuid>061a1011-b472-4a81-b258-d5305c953b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu-list-15-menuitem-12' and @href = '/users/db1dcee3-80e5-4ed6-bb83-7b8ce2629682/edit' and (text() = 'ubah' or . = 'ubah')]</value>
      <webElementGuid>79824fd5-aadf-41c7-9d44-904adf0ff031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
