<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_hapus</name>
   <tag></tag>
   <elementGuidId>f6bb1e85-b136-4910-89b5-734e7c362630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'hapus' or . = 'hapus')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-list-31-menuitem-29</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menu-list-31-menuitem-29']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1134e187-995b-4081-a764-108ed6723cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>601afbbd-75d8-49fb-95a6-cf590bcf89ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-list-31-menuitem-29</value>
      <webElementGuid>ee2f0775-65f3-411f-ba49-135a524a3e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>3ff6dd33-5eba-463b-a25f-eeec690a1f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d6b1ae44-e3b4-4c3e-916d-0f65330c2fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-menu__menuitem css-13c7rae</value>
      <webElementGuid>f151d11d-51b9-4ea3-87db-e3c149099ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c191ea29-7075-4173-964c-544866ec9982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hapus</value>
      <webElementGuid>79328a70-2476-43ce-b445-a4c71ad82d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-list-31-menuitem-29&quot;)</value>
      <webElementGuid>2d5c906d-ffef-4dd6-8646-8b2c0e9225f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menu-list-31-menuitem-29']</value>
      <webElementGuid>ae0053ea-a45b-4a32-8a55-f7ea0129f5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-list-31']/button</value>
      <webElementGuid>22be8e1d-7208-4002-a1ac-d80967d249c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ubah'])[1]/following::button[1]</value>
      <webElementGuid>0c0eb819-0263-4d67-b683-c9dcbd3ff09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kasir'])[2]/following::button[2]</value>
      <webElementGuid>175dbff7-2d12-43f8-aebb-6ffd0e448fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panji2'])[1]/preceding::button[1]</value>
      <webElementGuid>a3e9c28a-18f1-4298-9f37-939e1bcc5c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='panji12345@gmail.com'])[1]/preceding::button[1]</value>
      <webElementGuid>8cbc889a-4dcb-4d5f-9a1d-faec3b040fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='hapus']/parent::*</value>
      <webElementGuid>9f413e9b-64a4-49b9-af3a-ebbfacad0de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/button</value>
      <webElementGuid>41f5a421-a49b-41e0-ba09-b0dc11fcb7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'menu-list-31-menuitem-29' and (text() = 'hapus' or . = 'hapus')]</value>
      <webElementGuid>0260ede9-8a5f-4b73-acdb-c0475c6570a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
