<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_kasir_menu-button-2</name>
   <tag></tag>
   <elementGuidId>18df0b0a-426d-4261-a550-65801d2a66f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@type = 'button' and @class = 'chakra-button chakra-menu__menu-button css-pu8osu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-button-31</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menu-button-31']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ca79988-18b0-41b9-9bf9-8366814d4db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee3d741c-b760-4b48-b01d-b3c0a130a0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button chakra-menu__menu-button css-pu8osu</value>
      <webElementGuid>1228bef6-d68a-43dc-b9bd-bd24bf678747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-button-31</value>
      <webElementGuid>4c55bcf9-7766-41f6-811a-c2ba5b01a97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>368785ff-545d-4936-8f8e-92985422758b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>c03d9311-5838-46b0-bac3-7373ae257133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>menu-list-31</value>
      <webElementGuid>bf5db0ef-ee36-45db-ad54-32c927235e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-button-31&quot;)</value>
      <webElementGuid>b1ba23e4-3896-4099-9f5f-f51d73213e0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menu-button-31']</value>
      <webElementGuid>f3a4bfa6-d6a9-41f3-ab42-4fd3e7b53415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td[4]/button</value>
      <webElementGuid>ff98485b-bb1f-42cf-b987-7b3fd2bb3929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kasir'])[2]/following::button[1]</value>
      <webElementGuid>486379c8-0164-4ac2-bf86-7644b1c97f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='panji123@gmail.com'])[1]/following::button[1]</value>
      <webElementGuid>5f9aec32-2c69-4613-958c-bd5e9ceef089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ubah'])[1]/preceding::button[1]</value>
      <webElementGuid>efffb319-9ae2-4b50-bb74-85e67db4ae77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hapus'])[1]/preceding::button[1]</value>
      <webElementGuid>fe72908c-d63d-4247-b3c6-2d906d9b310b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/button</value>
      <webElementGuid>89a887de-ec4a-4e56-a031-a5688b6ec962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'menu-button-31']</value>
      <webElementGuid>7462bf73-91d5-4d55-9235-23063d800d68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
