<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_tambahnamaemailrolePanji2panji12345gmai_43ce7e</name>
   <tag></tag>
   <elementGuidId>f1a6a41c-f274-4308-a3fb-08a0b5ca00b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1t33j5j</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f5f68fa-e8a8-4796-8e29-269d20f50db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1t33j5j</value>
      <webElementGuid>6ad3c6a7-b971-4cd1-bf6f-40ce307dbd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tambahnamaemailrolePanji2panji12345@gmail.comkasirubahhapus&lt;></value>
      <webElementGuid>a45c9ed4-e6d5-4998-9a47-d8140d1c813d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1r35f0l&quot;]/div[@class=&quot;chakra-container css-9rmdie&quot;]/div[@class=&quot;css-1t33j5j&quot;]</value>
      <webElementGuid>0f38c8df-11f3-4ce0-805a-1bcb605f38ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>e15dc189-dc0c-4c12-9fbe-c738d433951d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dashboard'])[2]/following::div[1]</value>
      <webElementGuid>3099ebf1-5998-41c3-927b-371cb3c5decc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>6ed8d771-c0cc-45bf-a844-4862d98de1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'tambahnamaemailrolePanji2panji12345@gmail.comkasirubahhapus&lt;>' or . = 'tambahnamaemailrolePanji2panji12345@gmail.comkasirubahhapus&lt;>')]</value>
      <webElementGuid>3f27d631-5240-4a09-bf85-d5fa3ed93d26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
