<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_successitem diubah</name>
   <tag></tag>
   <elementGuidId>c9f7ae52-c087-4549-ad13-d4cff9e52e58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d78fa32c-12c3-45e3-9813-d1352f27177d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>d28d3219-49bb-4d94-a932-6e929f58c7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e34e8406-fe80-4a2c-a4f4-f811413d02bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>toast-1-title</value>
      <webElementGuid>e40c3f06-f0ee-4f68-9b1b-846106b5a5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-alert css-3b6enb</value>
      <webElementGuid>ab103752-f7ec-4496-bfc6-c147defdb528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>successitem diubah</value>
      <webElementGuid>6f6df43e-5b70-4f74-86bc-380a1f809ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-toast-manager-top-right&quot;)/li[@class=&quot;chakra-toast&quot;]/div[@class=&quot;chakra-toast__inner&quot;]/div[@id=&quot;1&quot;]</value>
      <webElementGuid>c8806534-30b6-488e-8d8e-4297d1dcb800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1']</value>
      <webElementGuid>66a25fd0-2115-4c88-a725-465c160ec8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='chakra-toast-manager-top-right']/li/div/div</value>
      <webElementGuid>5771bb03-2c52-4b08-a1b9-c3ba645a75b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/following::div[6]</value>
      <webElementGuid>c221c6c0-061e-4ea0-80d1-1c1dee8809cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div</value>
      <webElementGuid>eaca5ac8-93d2-407c-814b-58d54f2d2f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1' and (text() = 'successitem diubah' or . = 'successitem diubah')]</value>
      <webElementGuid>4e93264c-ded4-40ee-aae7-b7fb9c8b74ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='2']</value>
      <webElementGuid>451e859a-f8f6-4496-98f9-71adc9ed28c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[4]</value>
      <webElementGuid>e271404c-713a-4d67-acdd-fe0421594bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '2' and (text() = 'successitem diubah' or . = 'successitem diubah')]</value>
      <webElementGuid>81357a46-d1df-4932-8793-a549936f420f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
