<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_logout</name>
   <tag></tag>
   <elementGuidId>289f6233-e7b1-4c47-9aa0-00c4ed941a77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-list-14-menuitem-12</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='menu-list-14-menuitem-12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dfbf87a0-b62f-4b71-88c3-eb3a191dbef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc0d9d81-ee0c-4b77-9f95-5f9d2d084c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-list-14-menuitem-12</value>
      <webElementGuid>cc6876d7-41b7-4616-95ff-c8e194108a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>88b03ed8-01ea-4a15-ad5d-5244bcf9089f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c72f6257-31de-4aa2-97e9-72124f4b013f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-menu__menuitem css-vuzh5r</value>
      <webElementGuid>b3ab88d9-0d79-4996-b987-a4dd8432996e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>06a1ab36-35ed-441e-83fe-da720f069850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>logout</value>
      <webElementGuid>b3c72bc6-3a6e-495b-ae8e-816c2222cc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-list-14-menuitem-12&quot;)</value>
      <webElementGuid>e9635457-fea7-444c-a057-39df6953da3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='menu-list-14-menuitem-12']</value>
      <webElementGuid>20148b9d-4863-4b52-a8dd-9d027d8d13e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-list-14']/button[2]</value>
      <webElementGuid>82fd92fc-46d4-4b90-bc9d-d493959df504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panjimart'])[1]/following::button[1]</value>
      <webElementGuid>f8bc6038-5a00-46cb-9606-63108e9d0d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panjimart'])[2]/preceding::button[1]</value>
      <webElementGuid>bc2c3440-e649-442c-9960-ca5c1949a220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hai'])[1]/preceding::button[1]</value>
      <webElementGuid>2ab0fddc-158d-4679-8002-148b3a210c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='logout']/parent::*</value>
      <webElementGuid>2c12d60e-49a6-46c6-8408-b10757926595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4bccef26-4fa4-4766-930b-c480776fc9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'menu-list-14-menuitem-12' and (text() = 'logout' or . = 'logout')]</value>
      <webElementGuid>bfc0a9cd-4e0d-4cdf-ae06-338cae3060c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
