<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Panjimart</name>
   <tag></tag>
   <elementGuidId>8c67d526-25bf-4688-b503-98ca6a33c4b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-list-14-menuitem-11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu-list-14-menuitem-11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eaabbdd7-f2bf-4a94-ab24-909744fc6758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-list-14-menuitem-11</value>
      <webElementGuid>9318f674-53c8-4144-8453-544bda42f28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>bacdb21b-5da9-47b1-aff8-dd860ffdfe93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>db7ab49f-d069-415a-8c9f-2a493c2d7497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-menu__menuitem css-vuzh5r</value>
      <webElementGuid>15fdeeda-7149-46a3-b505-9cddd3d4200a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/users/2d59b20a-c206-42ff-8b9a-a6e1c07e3e1c/edit</value>
      <webElementGuid>6b0c3596-8f87-4b5c-bd9a-8678f2adbbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>994ed652-b8af-42e0-8fe9-5317e1eea1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Panjimart</value>
      <webElementGuid>d78c8629-8ed1-4a80-a512-2b4272b1b98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-list-14-menuitem-11&quot;)</value>
      <webElementGuid>140c1e83-4569-45ca-9959-387a8df43265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu-list-14-menuitem-11']</value>
      <webElementGuid>d42b9efa-fb81-4863-b1c4-3aa114045df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-list-14']/a</value>
      <webElementGuid>7c2e2a54-088d-4539-a66c-53fb94d0196e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Panjimart')]</value>
      <webElementGuid>57c81a38-3511-43e4-9cdb-f998730b354c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='P'])[1]/following::a[1]</value>
      <webElementGuid>272ca802-3c01-4b84-b480-f00891f9348c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/preceding::a[1]</value>
      <webElementGuid>6f886afa-bae7-4401-9231-91bbc5bf728c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panjimart'])[2]/preceding::a[1]</value>
      <webElementGuid>f5fea254-566a-4a96-bba6-234b721fc416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/users/2d59b20a-c206-42ff-8b9a-a6e1c07e3e1c/edit')]</value>
      <webElementGuid>70234a9a-98bd-4237-8425-fbc686f32271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>d91c28b6-fc89-47bf-a689-c2aec413c2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu-list-14-menuitem-11' and @href = '/users/2d59b20a-c206-42ff-8b9a-a6e1c07e3e1c/edit' and (text() = 'Panjimart' or . = 'Panjimart')]</value>
      <webElementGuid>4bbe305a-2233-407c-a0da-8c547fa83a33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
