<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama_nama</name>
   <tag></tag>
   <elementGuidId>dc3ed080-8160-49e4-8e25-0b1e0fb2d231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0618413-0037-4b00-97e7-148595ca5ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c4e7ad4-8596-4dad-9967-b5c410d0362a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data</name>
      <type>Main</type>
      <value>nama,Panjimart,function () { [native code] }</value>
      <webElementGuid>fa6ff5b1-5209-436e-9bb0-cf852fce2bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama</value>
      <webElementGuid>27210d08-dd27-407a-92bc-0e06aec4beb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-ksd4gw</value>
      <webElementGuid>29f37706-e140-48d8-a88f-5cb3e6efe94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Panjimart</value>
      <webElementGuid>7fa5f04a-8f7c-4d8e-aa1d-0560cb9ca297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nama&quot;)</value>
      <webElementGuid>77ca6d9a-59d1-4dd1-b5ba-8e275e4d6e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nama']</value>
      <webElementGuid>0e13974c-0ba5-48ee-8b07-31c9ab9f9dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>ce41eb44-510d-4058-959c-267ac5bb4734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3350b0b6-5e59-42c9-bacf-579dcc11e316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nama']</value>
      <webElementGuid>92f52246-385c-4498-9ecf-3145489ab1d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
